Vid/Entities/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Vid.Interfaces;

namespace Vid.Entities
{
    public class Category : IPrimaryProperties
    {
        public int Id { get; set; }

        [Required]
        [StringLength(200, MinimumLength = 2)]
        public string Title { get; set; }

        public string Description { get; set; }

        [Required]
        [Display(Name = "Thumbnail Image Path")]
        public string ThumbnailImagePath { get; set; }

        [ForeignKey("CategoryId")]
        public virtual ICollection<CategoryItem> CategoryItems { get; set; }

        [ForeignKey("CategoryId")]
        public virtual ICollection<UserCategory> UserCategory { get; set; }
    }
}

Vid/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Vid.Repository.Contract;
using Vid.ViewModel.CategoryVM;

namespace Vid.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategory _category;

        public CategoryController(ICategory category)
        {
            _category = category;
        }
        public async Task<IActionResult> Index()
        {
            var obj = await _category.GetAllCategories();
            return View(obj);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryIndex categoryIndex)
        {
            
            await _category.AddCategory(categoryIndex);
            return RedirectToAction("Index");
        }
    }
}

Vid/Areas/Admin/Controllers/CategoryItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Vid.Entities;
using Vid.Extensions;
using Vid.Models;
using Vid.Repository.Contract;
using Vid.ViewModel.CategoryItemVM;

namespace Vid.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryItemController : Controller
    {
        private readonly ICategoryItem _categoryItem;
        private readonly ApplicationDbContext _context;
        public CategoryItemController(ICategoryItem categoryItem, ApplicationDbContext applicationDbContext)
        {
            _context = applicationDbContext;
            _categoryItem = categoryItem;
        }

        public async Task<IActionResult> Index(int categoryId)
        {
            /*var ojj = await _categoryItem.GetAllItemCategories();
            var hum = _categoryItem.GetContentCatItemId(ojj, categoryId);*/
            var samp = await (from catitem in _context.CategoryItem
                             join content in _context.Content
                             on catitem.Id equals content.CategoryItem.Id
                             into gf
                             from getContentId in gf.DefaultIfEmpty()
                             where catitem.CategoryId == categoryId
                             select new CatItemIndex()
                             {
                                 CategoryId = categoryId,
                                 ContentId = (getContentId == null) ? 0 : getContentId.Id,
                                 MediaTypeId = catitem.MediaTypeId,
                                 Description = catitem.Description,
                                 Id = catitem.Id,
                                 DateTimeItemReleased = catitem.DateTimeItemReleased,
                                 Title = catitem.Title,
                             }).ToListAsync();

/*            var item = await _categoryItem.GetAllItemCategories();
            item = item.Where(q=> q.CategoryId == categoryId).ToList();

            var obj = item.Select(q => new CatItemIndex()
            {
                CategoryId= categoryId,
                ContentId =q.ContentId,
                MediaTypeId=q.MediaTypeId,
                Description=q.Description,
                Id=q.Id,
                DateTimeItemReleased=q.DateTimeItemReleased,
                Title=q.Title
            });
*/
            var model = new CatListItemIndex()
            {
                CatList = samp,
                CategoryId = categoryId
            };

            return View(model);
        }
        public async Task<IActionResult> Create(int categoryId)
        {
            List<MediaType> mediaTypes = await _context.MediaType.ToListAsync();
             
            var obj = new CatItemIndex()
            {
                CategoryId = categoryId,
                MediaTypes = mediaTypes.ConvertToSelectList(0)

            };
            return View(obj);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CatItemIndex catItemIndex)
        {
            await _categoryItem.AddCategoryItem(catItemIndex);
            return RedirectToAction("Index", new { categoryId = catItemIndex.CategoryId });
        }


        public async Task<IActionResult> Edit(int id)
        {
            List<MediaType> mediaTypes = await _context.MediaType.ToListAsync();
            var item = await _categoryItem.FindCategoryIdItem(id);

            if (item == null) return NotFound();

            item.MediaTypes = mediaTypes.ConvertToSelectList(item.MediaTypeId);

            return View(item);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CatItemIndex catItemIndex)
        {
            await _categoryItem.UpdateCategoryItem(catItemIndex);
            return RedirectToAction("Index", new { categoryId = catItemIndex.CategoryId });
        }
    }
}

Vid/Areas/Admin/Views/Category/Create.cshtml
@model Vid.Entities.Category

@{
    ViewData["Title"] = "Create";
}


<h4 class="text-center">Category</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" rows="2" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ThumbnailImagePath" class="control-label"></label>
                <input asp-for="ThumbnailImagePath" class="form-control" />
                <span asp-validation-for="ThumbnailImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Vid/Areas/Admin/Views/Category/Index.cshtml
@model IEnumerable<Vid.Entities.Category>

@{
    ViewData["Title"] = "Index";
}


<p>
    <a asp-action="Create" class="btn btn-outline-primary">Create</a>
    @*<partial name="_CreateButtonPartial" model="0" />*@
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ThumbnailImagePath)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ThumbnailImagePath)
                </td>
                <td>
                    @*<partial name="_RUDButtonsPartial" model="@item.Id">*@
                        <a asp-controller="CategoryItem" asp-action="Index" asp-route-categoryId="@item.Id" class="btn btn-outline-secondary btn-sm">Update Items</a>
                </td>
            </tr>
        }
    </tbody>
</table>