Vid/Controllers/CategoriesToUserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Vid.Entities;
using Vid.Models;
using Vid.ModelsTwo;
using Vid.Repository.Contract;

namespace Vid.Controllers
{
    [Authorize]
    public class CategoriesToUserController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IDataFunctions _dataFunctions;

        public CategoriesToUserController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            IDataFunctions dataFunctions)
        {
            _context = context;
            _userManager = userManager;
            _dataFunctions = dataFunctions;
        }
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserAsync(User).Result?.Id;
 

            var usersCurrentCategory = await CurrentCategory(userId);
            var ListofCourses = await CourseList();

            var model = new CategoryToChooseModel()
            {
                    UserId=userId,
                 Categories=ListofCourses,
                 CategoriesSelected= usersCurrentCategory
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(string[] CategoriesSelected)
        {
            var userId = _userManager.GetUserAsync(User).Result?.Id;

            var usersToAdd = (from categoryId in CategoriesSelected
                              select new UserCategory()
                            {
                                UserId = userId,
                                CategoryId = int.Parse(categoryId)
                            }).ToList();

            var usersToDelete = (from users in _context.UserCategory
                                 where users.UserId==userId
                                 select new UserCategory()
                                 {
                                     Id = users.Id,
                                     UserId = userId,
                                     CategoryId = users.CategoryId
                                 }).ToList();

            await _dataFunctions.UpdateUserCategoryEntityAsync(usersToAdd, usersToDelete);

            return RedirectToAction("Index", "Home");
        }
        private async Task<List<Category>> CourseList()
        {
            var ListofCourses = await (from category in _context.Category
                                       join catItem in _context.CategoryItem
                                       on category.Id equals catItem.CategoryId
                                       join content in _context.Content
                                       on catItem.Id equals content.CategoryItem.Id
                                       select new Category()
                                       {
                                           Id = category.Id,
                                           ThumbnailImagePath = category.ThumbnailImagePath,
                                           Description = category.Description,
                                           Title = category.Title,

                                       }).Distinct().ToListAsync();
            return ListofCourses;
        }
        private async Task<List<Category>> CurrentCategory(string userId)
        {
            var usersCurrentCategory = await (from user in _context.UserCategory

                                              where user.UserId == userId
                                              select new Category()
                                              {
                                                  Id = user.CategoryId
                                              }).ToListAsync();
            return usersCurrentCategory;
        }
    }
}

Vid/Controllers/ContentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Vid.Entities;
using Vid.Models;

namespace Vid.Controllers
{
    public class ContentController : Controller
    {
        //d
        private readonly ApplicationDbContext _context;

        public ContentController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int categoryItemId)
        {
            var content = await (from item in _context.Content
                                     where item.CategoryItem.Id == categoryItemId
                                     select new Content
                                     {
                                         Title = item.Title,
                                         VideoLink = item.VideoLink,
                                         HTMLContent = item.HTMLContent
                                     }).FirstOrDefaultAsync();

            return View(content);
        }
    }
}

Vid/Controllers/HomeController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Vid.Entities;
using Vid.Models;
using Vid.ModelsTwo;

namespace Vid.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public HomeController(ILogger<HomeController> logger,
            ApplicationDbContext context, SignInManager<ApplicationUser> signInManager,
            UserManager<ApplicationUser> userManager)
        {
            _logger = logger;
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;

        }

        private async Task<List<Category>> GetCategoriesThatHaveContent()
        {
            var obj = await (from category in _context.Category
                             join catItem in _context.CategoryItem
                             on category.Id equals catItem.CategoryId
                             join content in _context.Content
                             on catItem.Id equals content.CategoryItem.Id
                             select new Category()
                             {
                                 Id =category.Id,
                                 Title = category.Title,
                                 Description = category.Description,
                                 ThumbnailImagePath = category.ThumbnailImagePath
                             }).Distinct().ToListAsync();

            return obj;
        }

        public async Task<IActionResult> Index()
        {

            IEnumerable<CategoryItemDetailsModel> categoryDetails = null;
            IEnumerable<GroupedCategoryItemsByCategoryModel> groupCategoryItems = null;

            var categoryDetailModel = new CategoryDetailsModel();

            if (_signInManager.IsSignedIn(User))
            {
                var user = await _userManager.GetUserAsync(User);

                if (user != null)
                {
                    categoryDetails = await GetCategoryItemDetailsForUser(user.Id);
                    groupCategoryItems = GetGroupedCategoryItemsByCategory(categoryDetails);

                    categoryDetailModel.GroupedCategoryItemsByCategoryModels = groupCategoryItems;
                }
            }
            else
            {
                var categ = await GetCategoriesThatHaveContent();

                categoryDetailModel.Categories = categ;
            }


            return View(categoryDetailModel);
        }

        private IEnumerable<GroupedCategoryItemsByCategoryModel>
            GetGroupedCategoryItemsByCategory(IEnumerable<CategoryItemDetailsModel> categoryDetails)
        {
            var obj = from item in categoryDetails
                      group item by item.CategoryId into g
                      select new GroupedCategoryItemsByCategoryModel
                      {
                          Id = g.Key,
                          Title = g.Select(q => q.CategoryTitle).FirstOrDefault(),
                          Items = g
                      };
            // qwe
            return obj;
        }

        private async Task<IEnumerable<CategoryItemDetailsModel>> GetCategoryItemDetailsForUser(string id)
        {
            // If there`s no content, it wont query the data
            var obj = await (from category in _context.Category
                             join catItem in _context.CategoryItem
                             on category.Id equals catItem.CategoryId
                             join content in _context.Content
                             on catItem.Id equals content.CategoryItem.Id
                             join mediaType in _context.MediaType
                             on catItem.MediaTypeId equals mediaType.Id
                             join user in _context.UserCategory
                             on category.Id equals user.CategoryId
                             where user.UserId == id
                             select new CategoryItemDetailsModel()
                             {
                                 CategoryId = category.Id,
                                 CategoryItemDescription = catItem.Description,
                                 CategoryItemId = catItem.Id,
                                 CategoryItemTitle = catItem.Title,
                                 CategoryTitle = category.Title,
                                 MediaImagePath = mediaType.ThumbnailImagePath
                             }).ToListAsync();
            return obj;
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Vid/Views/Home/Index.cshtml
@model CategoryDetailsModel;
@{
    ViewData["Title"] = "Home Page";
}


@if (Model.GroupedCategoryItemsByCategoryModels != null)
{
    <div class="row">
        <div class="col-md-6">
            <h2>Your Courses</h2>
        </div>
        <div class="col-md-6 text-right">
           <a class="btn btn-outline-primary" asp-action="Index" asp-controller="CategoriesToUser">
               Choose your Courses
           </a>
        </div>
    </div>

    if (Model.GroupedCategoryItemsByCategoryModels.Count() > 0)
    {
        @foreach (var item in Model.GroupedCategoryItemsByCategoryModels)
        {
            <div class="card mt-2">
                <h4 class="card-header text-secondary bg-white" style="cursor:pointer" 
                    data-toggle="collapse" data-target="#collapse_@item.Id" aria-expanded="false"
                    aria-controls="collapse_@item.Id">

                    @item.Title
                </h4>
                <div id="collapse_@item.Id" class="collapse" aria-expanded="false" aria-controls="collapse_@item.Id">
                    <hr />
                    @foreach (var m in item.Items)
                    {
                        <div class="mt-2">

                            <img src="@m.MediaImagePath" width="100" height="100" class="img-thumbnail float-left mr-2" />
                            <h5 class="card-title mt-2">
                                <a class="text-dark" asp-controller="Content" asp-action="Index"
                                   asp-route-categoryItemId="@m.CategoryItemId">@m.CategoryItemTitle</a>
                            </h5>
                            <p class="card-text text-dark mt-2">
                                @m.CategoryItemDescription
                            </p>

                        </div>
                    }
                </div>
            </div>
        }
    }
    else
    {
        <h4 class="mt-2 text-warning">You are currently not matched with any courses</h4>
        // hello world
    }
}
else
{

   <partial name="_DefaultHomePageContentPartial" model="Model.Categories" />
}

Vid/Views/Home/IndexTwo.cshtml
@model Vid.ModelsTwo.CategModelWrapper;
@using Vid.Models;
@{
    ViewData["Title"] = "Home Page";
}


@if (Model.groupCategItemsDetail != null)
{
    <div class="row">
        <div class="col-md-6">
            <h2>Your Courses</h2>
        </div>
        <div class="col-md-6 text-right">
            <a asp-controller="CategoriesToUser" asp-action="Index" class="btn btn-outline-dark">Choose Courses</a>
        </div>
    </div>

    if (Model.groupCategItemsDetail.Count() > 0)
    {
        @foreach (var item in Model.groupCategItemsDetail)
        {
            <div class="card mt-2">
                <h4 class="card-header text-secondary bg-white" style="cursor:pointer"
                    data-toggle="collapse" data-target="#collapse_@item.Id" aria-expanded="false"
                    aria-controls="collapse_@item.Id">

                    @item.Title
                </h4>
                <div id="collapse_@item.Id" class="collapse" aria-expanded="false" aria-controls="collapse_@item.Id">
                    <hr />
                    @foreach (var m in item.GroupCategItems)
                    {
                        <div class="mt-2">

                            <img src="@m.VideoImage" width="100" height="100" class="img-thumbnail float-left mr-2" />
                            <h5 class="card-title mt-2">
                                <a class="text-dark" asp-controller="Content" asp-action="Index" asp-route-CategoryItemId="@m.CategoryItemsId">@m.CategoryItemsTitle</a>
                            </h5>
                            <p class="card-text text-dark mt-2">
                                @m.CategoryItemsDescription
                            </p>

                        </div>
                    }
                </div>
            </div>
        }
    }
    else
    {
        <h4 class="mt-2 text-warning">You are currently not matched with any courses</h4>

    }
}
else
{

    <h4 class="mt-2 text-warning">You are currently not matched with any courses</h4>
}